#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class Button;
                ref class TextBox;
            }
        }
    }
}

namespace PracticaFinalSeguridad
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class DHUserControl : public ::Windows::UI::Xaml::Controls::UserControl, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ K;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ yb;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ya;
        private: ::Windows::UI::Xaml::Controls::Button^ Button;
        private: ::Windows::UI::Xaml::Controls::TextBox^ primo;
        private: ::Windows::UI::Xaml::Controls::TextBox^ alpha;
        private: ::Windows::UI::Xaml::Controls::TextBox^ xa;
        private: ::Windows::UI::Xaml::Controls::TextBox^ xb;
    };
}

